<?php
?>
<div data-id="information-dialog-category" class="messages" style="display: none;">
    <div class="message message-notice">
        <div><?= /* @escapeNotVerified */ __('This operation can take a long time') ?></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "categoryForm": {"refreshUrl": "<?= /* @escapeNotVerified */ $block->getRefreshPathUrl() ?>"}
        }
    }
</script>
