var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,d,e){b instanceof String&&(b=String(b));for(var l=b.length,g=0;g<l;g++){var p=b[g];if(d.call(e,p,g,b))return{i:g,v:p}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,e){if(b==Array.prototype||b==Object.prototype)return b;b[d]=e.value;return b};$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<b.length;++d){var e=b[d];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,d){var e=$jscomp.propertyToPolyfillSymbol[d];if(null==e)return b[d];e=b[e];return void 0!==e?e:b[d]};
$jscomp.polyfill=function(b,d,e,l){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,d,e,l):$jscomp.polyfillUnisolated(b,d,e,l))};$jscomp.polyfillUnisolated=function(b,d,e,l){e=$jscomp.global;b=b.split(".");for(l=0;l<b.length-1;l++){var g=b[l];if(!(g in e))return;e=e[g]}b=b[b.length-1];l=e[b];d=d(l);d!=l&&null!=d&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(b,d,e,l){var g=b.split(".");b=1===g.length;l=g[0];l=!b&&l in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var p=0;p<g.length-1;p++){var t=g[p];if(!(t in l))return;l=l[t]}g=g[g.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?l[g]:null;d=d(e);null!=d&&(b?$jscomp.defineProperty($jscomp.polyfills,g,{configurable:!0,writable:!0,value:d}):d!==e&&($jscomp.propertyToPolyfillSymbol[g]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(g):$jscomp.POLYFILL_PREFIX+g,g=
$jscomp.propertyToPolyfillSymbol[g],$jscomp.defineProperty(l,g,{configurable:!0,writable:!0,value:d})))};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(d,e){return $jscomp.findInternal(this,d,e).v}},"es6","es3");
define("underscore Magento_Ui/js/lib/view/utils/async mage/template uiRegistry Magento_Ui/js/form/element/abstract Magento_Ui/js/modal/confirm Magento_Ui/js/modal/alert jquery/ui mage/adminhtml/wysiwyg/widget".split(" "),function(b,d,e,l,g,p,t){d(function(c){c.widget("eloom.lookbookBuilder",{options:{elementName:"",btnAddImage:"[data-role=lb-add-image]",btnAddProd:"[data-role=lb-add-product]",btnReset:"[data-role=lb-reset]",imgWrap:"[data-role=image-wrap]",dataPoints:"[data-role=data-points]",pdPoint:"[data-role=pd-point]",
canvas:"[data-role=canvas]",insertProductText:"Insert Product",input:null},_create:function(){this._assignVariables();this._bindEvents()},_assignVariables:function(){var a=this.options;this.$btnAddImage=c(a.btnAddImage,this.element);this.$btnAddProd=c(a.btnAddProd,this.element);this.$imgWrap=c(a.imgWrap,this.element);this.$dataPoints=c(a.dataPoints,this.element);this.$input=a.input;this.$canvas=c(a.canvas,this.element);this._createForm();this._initCanvas()},_createForm:function(){var a=this.options;
this.$formWrap=c("<div>").css("display","none").appendTo("body");this.$iframe=c("<iframe>",{name:"upload_iframe_"+a.elementName}).appendTo(this.$formWrap);this.$productInput=c("<input>",{id:"product_input_"+a.elementName+"value",type:"hidden"}).appendTo(this.$formWrap);this.$productLabel=c("<div>",{id:"product_input_"+a.elementName+"label"}).appendTo(this.$formWrap);this.$form=c("<form>",{target:"upload_iframe_"+a.elementName,method:"post",enctype:"multipart/form-data",class:"ignore-validate",action:a.uploadUrl}).appendTo(this.$formWrap);
this.$inputFile=c("<input>",{type:"file",name:"datafile",class:"lookbook_file"}).appendTo(this.$form);c("<input>",{type:"hidden",name:"form_key",value:FORM_KEY}).appendTo(this.$form)},_bindEvents:function(){var a=this,f=this.options;this.element.on("click",f.btnAddImage,function(){a.$inputFile.click()});this.$inputFile.on("change",function(){c("body").loader("show");a.$iframe.off("load");a.$iframe.on("load",function(){c("body").loader("hide");var h=c.parseJSON(c(this).contents().find("body").html()),
m=h.swatch_path+h.file_path;0==a.$imgWrap.find("img").length&&a.$imgWrap.append(c("<img>"));var k=a.$imgWrap.find("img");k.attr("src",m);k.attr("data-filepath",h.file_path);var n=new Image;c(n).on("load",function(){var q=n.height;k.attr("data-width",n.width);k.attr("data-height",q)});n.src=m});a.$form.submit();c(this).val("")});this.element.on("click",f.btnAddProd,function(){a.$imgWrap.find("img").length?a._addNewPoint(null,0,0):t({title:"Message",content:"You need to insert an image first!"})});
this.element.on("click",f.btnReset,function(){p({title:"Reset",content:"Are you sure to reset? Item image and all added products will be removed.",actions:{confirm:function(){a.$imgWrap.empty();a.$dataPoints.empty()}}})});c("body").on("processStart",function(h){h=a._toJson();a.$input.val(JSON.stringify(h)).trigger("change")});this.$productInput.on("product_updated",function(){if(a.$currentPoint&&a.$productInput.val()){0==a.$currentPoint.find(".product-name").length&&a.$currentPoint.find(".pd-point-inner").append(c('<div class="product-name">'));
var h=a.$currentPoint.find(".product-name"),m=a.$productLabel.text(),k=a.$productInput.val();k=k.split("/");k=k[1];m="<strong>"+k+":</strong> "+m.split("/").last();a.$currentPoint.attr("data-productId",k);h.html(m);h.fadeIn(300,"linear",function(){setTimeout(function(){h.fadeOut(300,"linear",function(){h.css("display","")})},500)});a.$currentPoint=!1}})},_addNewPoint:function(a,f,h){var m=this,k=c("<div>",{"data-role":"pd-point","class":"pd-point","data-productId":a}).css({left:f,top:h});k.appendTo(m.$dataPoints);
f=c('<div class="pd-point-inner">').appendTo(k);h=c('<div class="pd-add-product" title="Select product"></div>').appendTo(f);var n=c('<div class="pd-point-rm" title="Remove this point">').appendTo(f);a&&(productName="<strong>"+a+":</strong> "+eloom.products[a].name,f.append(c('<div class="product-name">').html(productName)));n.on("click",function(){p({title:"Delete Point",content:"Are you sure to remove this point?",actions:{confirm:function(){k.remove()}}})});h.on("click",function(){m.$currentPoint=
k;m._pickProduct(k)});k.draggable({containment:m.$dataPoints,scroll:!1})},_pickProduct:function(a){a=this.options;window.productChooser||(window.productChooser=new WysiwygWidget.chooser("product_input_"+a.elementName,eloom.productUrl+"?uniq_id=productChooser",{buttons:{open:"Select Product...",close:"Close"}}),window.productChooser.oldClose=window.productChooser.close,window.productChooser.close=function(f){window.productChooser.oldClose();c(this.getElement()).trigger("product_updated")});window.productChooser.choose()},
_toJson:function(){var a=this.options,f={};if(this.$imgWrap.find("img").length){var h=this.$imgWrap.find("img");f.image=h.data("filepath");f.width=h.data("width");f.height=h.data("height")}else f.image=null,f.width=0,f.height=1;f.points=[];var m=parseFloat(this.$canvas.width()),k=parseFloat(this.$canvas.height());this.$dataPoints.find(a.pdPoint).each(function(){var n=c(this),q=n.css("left"),r=n.css("top");q=100*parseFloat(q)/m;r=100*parseFloat(r)/k;n={left:q,top:r,productId:n.attr("data-productid")};
f.points.push(n)});return f},_initCanvas:function(){var a=this,f=this.options,h=this.$input.val()?JSON.parse(this.$input.val()):null;if(h){var m=h.image;if(m){f=eloom.mediaUrl+f.mediaUrl+m;var k=c("<img>",{src:f,"data-filepath":m}).appendTo(a.$imgWrap),n=new Image;c(n).on("load",function(){var q=n.height;k.attr("data-width",n.width);k.attr("data-height",q)});n.src=f}h.points.length&&c.each(h.points,function(q,r){a._addNewPoint(r.productId,r.left+"%",r.top+"%")})}}})});return g.extend({defaults:{elementId:0,
prefixName:"",prefixElementName:"",elementName:"",value:"",uploadUrl:""},initialize:function(){this._super().initOldCode();return this},initConfig:function(){this._super();return this},initOldCode:function(){var c=this;d.async("#"+this.uid,function(a){a=d(a);var f=a.parents("[data-role=lookbook-builder]").first();d.eloom.lookbookBuilder({elementName:c.inputName,input:a,uploadUrl:c.uploadUrl,mediaUrl:c.mediaUrl},f)})}})});
