var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var h=a[d];if(b.call(c,h,d,a))return{i:d,v:h}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))return;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<d.length-1;h++){var f=d[h];if(!(f in e))return;e=e[f]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
define(["jquery","owlslider"],function(a){a.widget("eloom.featuredLooks",{options:{productWidth:200,dots:!0,nav:!1,top:40},_create:function(){this._assignVariables();this._bindEvents()},_assignVariables:function(){var b=this.options;this.$points=this.element.find('[data-role="small-item-points"]');this.$products=this.element.find('[data-role="product-html-data"]');this.$modal=a('<div class="mb-look-container">').appendTo("body");this.sliderConfig=b.sliderConfig;this.sliderConfig.rtl=a("body").hasClass("rtl-layout");
this.sliderConfig.lazyLoad=!0;this.sliderConfig.navElement="div";this.$lookSlider=this.element.find('[data-role="look-slider"]').owlCarousel(this.sliderConfig);b.productWidth=parseFloat(b.productWidth);this.element.find('[data-role="slider-loader"]').remove()},_bindEvents:function(){var b=this,c=this.options;this.$modal.modal({innerScroll:!1,modalClass:"mb-look-modal "+b.element.parents(".base-slider").first().attr("class"),buttons:[],opened:function(){}});this.$points.find("[data-productid]").each(function(){var d=
a(this),h=d.data("productid");$product=b.$products.find('[data-productid="'+h+'"]');if($product.length){var f=a('<div class="product-container lb-modal-container">').hide().css({position:"absolute"});f.appendTo(d);var p=$product.clone().appendTo(f),n=parseFloat(d.innerWidth()),k=d.parents('[data-role="item"]').first();d.find(".item-point").click(function(){d.toggleClass("active");p.find("img.owl-lazy").each(function(){a(this).attr("src",a(this).data("src"));a(this).removeClass("owl-lazy")});if(768<=
window.innerWidth){var g=d.data("left");g=d.data("top");f.css({height:"auto",width:c.productWidth,left:-(c.productWidth-n)/2,top:c.top});f.fadeToggle(300,"linear").toggleClass("drop-active");var l=parseFloat(f.offset().left),m=parseFloat(k.offset().left),q=parseFloat(k.innerWidth()),r=parseFloat(f.offset().top),t=parseFloat(f.innerHeight()),u=parseFloat(k.offset().top),v=parseFloat(k.innerHeight());l<m&&(g=-(c.productWidth-n)/2+(m-l)+10,f.css({left:g+"px"}));l+c.productWidth>m+q&&(g=-(c.productWidth-
n)/2-(l+c.productWidth-(m+q))-10,f.css({left:g+"px"}));r+t>u+v&&(g=c.top-(r+t-(u+v))-10,f.css({top:g+"px"}))}else p.clone().appendTo(b.$modal.empty()),b.$modal.modal("openModal"),a("body").trigger("contentUpdated")});a("body").on("click",function(g){768<=window.innerWidth&&d.hasClass("active")&&(g=a(g.target),g.is(d)||d.has(g).length||(d.removeClass("active"),f.hide().removeClass("drop-active")))})}});a("body").trigger("contentUpdated");var e=window.innerWidth;a(window).on("resize",function(){window.innerWidth!=
e&&(e=window.innerWidth,768>e?b.element.find(".product-container").hide().parents(".item-hook").first().removeClass("active"):b.$modal.modal("closeModal"))})}});return a.eloom.featuredLooks});
