var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var h=e[f];if(!(h in d))return;d=d[h]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
define(["jquery","jquery-ui-modules/widget","owlslider"],function(a){a.widget("eloom.lookbook",{options:{items:"[data-role=item]",itemModal:"[data-role=item-modal]",smallItemPoints:"[data-role=small-item-points]",largeItemPoints:"[data-role=large-item-points]",productHtmlData:"[data-role=product-html-data]",modalContainer:"[data-role=modal-container]",modalClose:"[data-role=close-modal]",modalInner:"[data-role=modal-inner]",modalContent:"[data-role=modal-content]",modalSlider:"[data-role=modal-slider]",
productSlider:"[data-role=product-slider]"},_create:function(){this._assignVariables();this._prepareHtml();this._bindEvents()},_assignVariables:function(){var b=this.options;this.$items=a(b.items,this.element);this.$itemModal=a(b.itemModal,this.element);this.$productHtmlData=a(b.productHtmlData,this.element);this.$modalContainer=a(b.modalContainer,this.element);this.$modalSlider=a(b.modalSlider,this.element);this.$modalContainer.addClass("first-load");this.rtl=a("body").hasClass("rtl-layout")},_prepareHtml:function(){var b=
this,c=this.options;this.$items.each(function(d,e){e=a(this);e.attr("data-itemid",d);d=a(c.itemModal,e).attr("data-modalid",d);d.find(c.largeItemPoints).html()||(e=e.find(c.smallItemPoints).html(),d.find(c.largeItemPoints).html(e));d.appendTo(b.$modalSlider).css("display","");var f=a(c.productSlider,d);if(d=f.data("productid"))d=d.toString().split(","),a.each(d,function(h,g){g=b.$productHtmlData.find("[data-productid="+g+"]");g.length&&g.clone().appendTo(f).attr("data-slideid",h)}),f.addClass("owl-carousel").owlCarousel({responsiveClass:!0,
responsive:{1900:{items:3},1600:{items:2},768:{items:2},480:{items:2},0:{items:2}},responsiveRefreshRate:500,nav:!0,dots:!0,margin:20,lazyLoad:!0,navElement:"div",rtl:b.rtl})});this.$modalSlider.addClass("owl-carousel");this.$modalSlider.owlCarousel({items:1,nav:!0,dots:!1,lazyLoad:!0,mouseDrag:!1,touchDrag:!1,navElement:"div",rtl:b.rtl});this.sliderData=this.$modalSlider.data("owl.carousel");window.sliderData=this.sliderData},_bindEvents:function(){var b=this,c=this.options;this.$items.each(function(d,
e){var f=a(this);f.on("click",function(){var h=f.data("itemid");b.$modalContainer.removeClass("_hide fadeOut").addClass("animated fadeIn");a("body").addClass("lb-modal-open");b.sliderData.to(h,0,!0);b.$modalContainer.hasClass("first-load")&&setTimeout(function(){b.$modalContainer.removeClass("first-load")},400)})});this.$modalContainer.on("click",c.modalClose,function(){b.$modalContainer.removeClass("animated fadeIn").addClass("animated fadeOut");a("body").removeClass("lb-modal-open");setTimeout(function(){b.$modalContainer.addClass("_hide")},
500)});a(c.itemModal,this.element).each(function(){var d=a(this),e=a(c.productSlider,d);d.find(".item-point").each(function(){var f=a(this),h=f.data("productid"),g=a("[data-productid="+h+"]",e),l=g.data("slideid");f.attr("href",g.data("href"));g.find("[data-role=product-number]").text(f.text());h=function(){g.parents(".owl-item").first().hasClass("active")||e.data("owl.carousel").to(l,0,!0);e.find("[data-productid]").addClass("product-hide");g.addClass("product-active").removeClass("product-hide");
f.addClass("point-active").siblings().addClass("point-disabled")};var k=function(){g.removeClass("product-active");e.find(".product-hide").removeClass("product-hide");f.removeClass("point-active").siblings().removeClass("point-disabled")};f.hover(h,k);g.hover(h,k)})})}});return a.eloom.lookbook});
